name: Terraform Provisioning

on:
  push:
    branches:
      - main  # or your infra branch

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-creds.json

      - name: Terraform Init
      
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
